<a class="c-drop-btn" href="javascript:void(0)" data-dropdown="hover1" data-options="is_hover: true; hover_timeout: 5000">
  <span class="help">
    <span class="icon-smile"></span>
  </span>
</a>
<div id="hover1" class="f-dropdown c-picker is-open" data-dropdown-content>
  <div class="c-picker__inner ">
    <div class="c-picker__body  cuScroll">
      <div class=" c-picker__title">Frequently used</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="thumbs_up">👍</span>
        <span class="js-emoji c-picker__emoji" title="-1">👎</span>
        <span class="js-emoji c-picker__emoji" title="sob">😭</span>
        <span class="js-emoji c-picker__emoji" title="confused">😕</span>
        <span class="js-emoji c-picker__emoji" title="neutral_face">😐</span>
        <span class="js-emoji c-picker__emoji" title="blush">😊</span>
        <span class="js-emoji c-picker__emoji" title="heart_eyes">😍</span>
      </div>
      <div class=" c-picker__title">People</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="smile">😄</span>
        <span class="js-emoji c-picker__emoji" title="smiley">😃</span>
        <span class="js-emoji c-picker__emoji" title="grinning">😀</span>
        <span class="js-emoji c-picker__emoji" title="blush">😊</span>
        <span class="js-emoji c-picker__emoji" title="wink">😉</span>
        <span class="js-emoji c-picker__emoji" title="heart_eyes">😍</span>
        <span class="js-emoji c-picker__emoji" title="kissing_heart">😘</span>
        <span class="js-emoji c-picker__emoji" title="kissing_closed_eyes">😚</span>
        <span class="js-emoji c-picker__emoji" title="kissing">😗</span>
        <span class="js-emoji c-picker__emoji" title="kissing_smiling_eyes">😙</span>
        <span class="js-emoji c-picker__emoji" title="stuck_out_tongue_winking_eye">😜</span>
        <span class="js-emoji c-picker__emoji" title="stuck_out_tongue_closed_eyes">😝</span>
        <span class="js-emoji c-picker__emoji" title="stuck_out_tongue">😛</span>
        <span class="js-emoji c-picker__emoji" title="flushed">😳</span>
        <span class="js-emoji c-picker__emoji" title="grin">😁</span>
        <span class="js-emoji c-picker__emoji" title="pensive">😔</span>
        <span class="js-emoji c-picker__emoji" title="relieved">😌</span>
        <span class="js-emoji c-picker__emoji" title="unamused">😒</span>
        <span class="js-emoji c-picker__emoji" title="disappointed">😞</span>
        <span class="js-emoji c-picker__emoji" title="persevere">😣</span>
        <span class="js-emoji c-picker__emoji" title="cry">😢</span>
        <span class="js-emoji c-picker__emoji" title="joy">😂</span>
        <span class="js-emoji c-picker__emoji" title="sob">😭</span>
        <span class="js-emoji c-picker__emoji" title="sleepy">😪</span>
        <span class="js-emoji c-picker__emoji" title="disappointed_relieved">😥</span>
        <span class="js-emoji c-picker__emoji" title="cold_sweat">😰</span>
        <span class="js-emoji c-picker__emoji" title="sweat_smile">😅</span>
        <span class="js-emoji c-picker__emoji" title="sweat">😓</span>
        <span class="js-emoji c-picker__emoji" title="weary">😩</span>
        <span class="js-emoji c-picker__emoji" title="tired_face">😫</span>
        <span class="js-emoji c-picker__emoji" title="fearful">😨</span>
        <span class="js-emoji c-picker__emoji" title="scream">😱</span>
        <span class="js-emoji c-picker__emoji" title="angry">😠</span>
        <span class="js-emoji c-picker__emoji" title="rage">😡</span>
        <span class="js-emoji c-picker__emoji" title="triumph">😤</span>
        <span class="js-emoji c-picker__emoji" title="confounded">😖</span>
        <span class="js-emoji c-picker__emoji" title="laughing">😆</span>
        <span class="js-emoji c-picker__emoji" title="yum">😋</span>
        <span class="js-emoji c-picker__emoji" title="mask">😷</span>
        <span class="js-emoji c-picker__emoji" title="sunglasses">😎</span>
        <span class="js-emoji c-picker__emoji" title="sleeping">😴</span>
        <span class="js-emoji c-picker__emoji" title="dizzy_face">😵</span>
        <span class="js-emoji c-picker__emoji" title="astonished">😲</span>
        <span class="js-emoji c-picker__emoji" title="worried">😟</span>
        <span class="js-emoji c-picker__emoji" title="frowning">😦</span>
        <span class="js-emoji c-picker__emoji" title="anguished">😧</span>
        <span class="js-emoji c-picker__emoji" title="imp">👿</span>
        <span class="js-emoji c-picker__emoji" title="open_mouth">😮</span>
        <span class="js-emoji c-picker__emoji" title="grimacing">😬</span>
        <span class="js-emoji c-picker__emoji" title="neutral_face">😐</span>
        <span class="js-emoji c-picker__emoji" title="confused">😕</span>
        <span class="js-emoji c-picker__emoji" title="hushed">😯</span>
        <span class="js-emoji c-picker__emoji" title="smirk">😏</span>
        <span class="js-emoji c-picker__emoji" title="expressionless">😑</span>
        <span class="js-emoji c-picker__emoji" title="man_with_gua_pi_mao">👲</span>
        <span class="js-emoji c-picker__emoji" title="man_with_turban">👳</span>
        <span class="js-emoji c-picker__emoji" title="cop">👮</span>
        <span class="js-emoji c-picker__emoji" title="construction_worker">👷</span>
        <span class="js-emoji c-picker__emoji" title="guardsman">💂</span>
        <span class="js-emoji c-picker__emoji" title="baby">👶</span>
        <span class="js-emoji c-picker__emoji" title="boy">👦</span>
        <span class="js-emoji c-picker__emoji" title="girl">👧</span>
        <span class="js-emoji c-picker__emoji" title="man">👨</span>
        <span class="js-emoji c-picker__emoji" title="woman">👩</span>
        <span class="js-emoji c-picker__emoji" title="older_man">👴</span>
        <span class="js-emoji c-picker__emoji" title="older_woman">👵</span>
        <span class="js-emoji c-picker__emoji" title="person_with_blond_hair">👱</span>
        <span class="js-emoji c-picker__emoji" title="angel">👼</span>
        <span class="js-emoji c-picker__emoji" title="princess">👸</span>
        <span class="js-emoji c-picker__emoji" title="smiley_cat">😺</span>
        <span class="js-emoji c-picker__emoji" title="smile_cat">😸</span>
        <span class="js-emoji c-picker__emoji" title="heart_eyes_cat">😻</span>
        <span class="js-emoji c-picker__emoji" title="kissing_cat">😽</span>
        <span class="js-emoji c-picker__emoji" title="smirk_cat">😼</span>
        <span class="js-emoji c-picker__emoji" title="scream_cat">🙀</span>
        <span class="js-emoji c-picker__emoji" title="crying_cat_face">😿</span>
        <span class="js-emoji c-picker__emoji" title="joy_cat">😹</span>
        <span class="js-emoji c-picker__emoji" title="pouting_cat">😾</span>
        <span class="js-emoji c-picker__emoji" title="japanese_ogre">👹</span>
        <span class="js-emoji c-picker__emoji" title="japanese_goblin">👺</span>
        <span class="js-emoji c-picker__emoji" title="see_no_evil">🙈</span>
        <span class="js-emoji c-picker__emoji" title="hear_no_evil">🙉</span>
        <span class="js-emoji c-picker__emoji" title="speak_no_evil">🙊</span>
        <span class="js-emoji c-picker__emoji" title="skull">💀</span>
        <span class="js-emoji c-picker__emoji" title="alien">👽</span>
        <span class="js-emoji c-picker__emoji" title="hankey">💩</span>
        <span class="js-emoji c-picker__emoji" title="fire">🔥</span>
        <span class="js-emoji c-picker__emoji" title="sparkles">✨</span>
        <span class="js-emoji c-picker__emoji" title="star2">🌟</span>
        <span class="js-emoji c-picker__emoji" title="dizzy">💫</span>
        <span class="js-emoji c-picker__emoji" title="boom">💥</span>
        <span class="js-emoji c-picker__emoji" title="anger">💢</span>
        <span class="js-emoji c-picker__emoji" title="sweat_drops">💦</span>
        <span class="js-emoji c-picker__emoji" title="droplet">💧</span>
        <span class="js-emoji c-picker__emoji" title="zzz">💤</span>
        <span class="js-emoji c-picker__emoji" title="dash">💨</span>
        <span class="js-emoji c-picker__emoji" title="ear">👂</span>
        <span class="js-emoji c-picker__emoji" title="eyes">👀</span>
        <span class="js-emoji c-picker__emoji" title="nose">👃</span>
        <span class="js-emoji c-picker__emoji" title="tongue">👅</span>
        <span class="js-emoji c-picker__emoji" title="lips">👄</span>
        <span class="js-emoji c-picker__emoji" title="thumbs_up">👍</span>
        <span class="js-emoji c-picker__emoji" title="-1">👎</span>
        <span class="js-emoji c-picker__emoji" title="ok_hand">👌</span>
        <span class="js-emoji c-picker__emoji" title="facepunch">👊</span>
        <span class="js-emoji c-picker__emoji" title="fist">✊</span>
        <span class="js-emoji c-picker__emoji" title="wave">👋</span>
        <span class="js-emoji c-picker__emoji" title="hand">✋</span>
        <span class="js-emoji c-picker__emoji" title="open_hands">👐</span>
        <span class="js-emoji c-picker__emoji" title="point_up_2">👆</span>
        <span class="js-emoji c-picker__emoji" title="point_down">👇</span>
        <span class="js-emoji c-picker__emoji" title="point_right">👉</span>
        <span class="js-emoji c-picker__emoji" title="point_left">👈</span>
        <span class="js-emoji c-picker__emoji" title="raised_hands">🙌</span>
        <span class="js-emoji c-picker__emoji" title="pray">🙏</span>
        <span class="js-emoji c-picker__emoji" title="clap">👏</span>
        <span class="js-emoji c-picker__emoji" title="muscle">💪</span>
        <span class="js-emoji c-picker__emoji" title="walking">🚶</span>
        <span class="js-emoji c-picker__emoji" title="runner">🏃</span>
        <span class="js-emoji c-picker__emoji" title="dancer">💃</span>
        <span class="js-emoji c-picker__emoji" title="couple">👫</span>
        <span class="js-emoji c-picker__emoji" title="family">👪</span>
        <span class="js-emoji c-picker__emoji" title="couplekiss">💏</span>
        <span class="js-emoji c-picker__emoji" title="couple_with_heart">💑</span>
        <span class="js-emoji c-picker__emoji" title="dancers">👯</span>
        <span class="js-emoji c-picker__emoji" title="ok_woman">🙆</span>
        <span class="js-emoji c-picker__emoji" title="no_good">🙅</span>
        <span class="js-emoji c-picker__emoji" title="information_desk_person">💁</span>
        <span class="js-emoji c-picker__emoji" title="raising_hand">🙋</span>
        <span class="js-emoji c-picker__emoji" title="massage">💆</span>
        <span class="js-emoji c-picker__emoji" title="haircut">💇</span>
        <span class="js-emoji c-picker__emoji" title="nail_care">💅</span>
        <span class="js-emoji c-picker__emoji" title="bride_with_veil">👰</span>
        <span class="js-emoji c-picker__emoji" title="person_with_pouting_face">🙎</span>
        <span class="js-emoji c-picker__emoji" title="person_frowning">🙍</span>
        <span class="js-emoji c-picker__emoji" title="bow">🙇</span>
        <span class="js-emoji c-picker__emoji" title="tophat">🎩</span>
        <span class="js-emoji c-picker__emoji" title="crown">👑</span>
        <span class="js-emoji c-picker__emoji" title="womans_hat">👒</span>
        <span class="js-emoji c-picker__emoji" title="athletic_shoe">👟</span>
        <span class="js-emoji c-picker__emoji" title="mans_shoe">👞</span>
        <span class="js-emoji c-picker__emoji" title="sandal">👡</span>
        <span class="js-emoji c-picker__emoji" title="high_heel">👠</span>
        <span class="js-emoji c-picker__emoji" title="boot">👢</span>
        <span class="js-emoji c-picker__emoji" title="shirt">👕</span>
        <span class="js-emoji c-picker__emoji" title="necktie">👔</span>
        <span class="js-emoji c-picker__emoji" title="womans_clothes">👚</span>
        <span class="js-emoji c-picker__emoji" title="dress">👗</span>
        <span class="js-emoji c-picker__emoji" title="running_shirt_with_sash">🎽</span>
        <span class="js-emoji c-picker__emoji" title="jeans">👖</span>
        <span class="js-emoji c-picker__emoji" title="kimono">👘</span>
        <span class="js-emoji c-picker__emoji" title="bikini">👙</span>
        <span class="js-emoji c-picker__emoji" title="briefcase">💼</span>
        <span class="js-emoji c-picker__emoji" title="handbag">👜</span>
        <span class="js-emoji c-picker__emoji" title="pouch">👝</span>
        <span class="js-emoji c-picker__emoji" title="purse">👛</span>
        <span class="js-emoji c-picker__emoji" title="eyeglasses">👓</span>
        <span class="js-emoji c-picker__emoji" title="ribbon">🎀</span>
        <span class="js-emoji c-picker__emoji" title="closed_umbrella">🌂</span>
        <span class="js-emoji c-picker__emoji" title="lipstick">💄</span>
        <span class="js-emoji c-picker__emoji" title="yellow_heart">💛</span>
        <span class="js-emoji c-picker__emoji" title="blue_heart">💙</span>
        <span class="js-emoji c-picker__emoji" title="purple_heart">💜</span>
        <span class="js-emoji c-picker__emoji" title="green_heart">💚</span>
        <span class="js-emoji c-picker__emoji" title="broken_heart">💔</span>
        <span class="js-emoji c-picker__emoji" title="heartpulse">💗</span>
        <span class="js-emoji c-picker__emoji" title="heartbeat">💓</span>
        <span class="js-emoji c-picker__emoji" title="two_hearts">💕</span>
        <span class="js-emoji c-picker__emoji" title="sparkling_heart">💖</span>
        <span class="js-emoji c-picker__emoji" title="revolving_hearts">💞</span>
        <span class="js-emoji c-picker__emoji" title="cupid">💘</span>
        <span class="js-emoji c-picker__emoji" title="love_letter">💌</span>
        <span class="js-emoji c-picker__emoji" title="kiss">💋</span>
        <span class="js-emoji c-picker__emoji" title="ring">💍</span>
        <span class="js-emoji c-picker__emoji" title="gem">💎</span>
        <span class="js-emoji c-picker__emoji" title="bust_in_silhouette">👤</span>
        <span class="js-emoji c-picker__emoji" title="speech_balloon">💬</span>
        <span class="js-emoji c-picker__emoji" title="footprints">👣</span>
      </div>
      <div class=" c-picker__title">Nature</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="dog">🐶</span>
        <span class="js-emoji c-picker__emoji" title="wolf">🐺</span>
        <span class="js-emoji c-picker__emoji" title="cat">🐱</span>
        <span class="js-emoji c-picker__emoji" title="mouse">🐭</span>
        <span class="js-emoji c-picker__emoji" title="hamster">🐹</span>
        <span class="js-emoji c-picker__emoji" title="rabbit">🐰</span>
        <span class="js-emoji c-picker__emoji" title="frog">🐸</span>
        <span class="js-emoji c-picker__emoji" title="tiger">🐯</span>
        <span class="js-emoji c-picker__emoji" title="koala">🐨</span>
        <span class="js-emoji c-picker__emoji" title="bear">🐻</span>
        <span class="js-emoji c-picker__emoji" title="pig">🐷</span>
        <span class="js-emoji c-picker__emoji" title="pig_nose">🐽</span>
        <span class="js-emoji c-picker__emoji" title="cow">🐮</span>
        <span class="js-emoji c-picker__emoji" title="boar">🐗</span>
        <span class="js-emoji c-picker__emoji" title="monkey_face">🐵</span>
        <span class="js-emoji c-picker__emoji" title="monkey">🐒</span>
        <span class="js-emoji c-picker__emoji" title="horse">🐴</span>
        <span class="js-emoji c-picker__emoji" title="sheep">🐑</span>
        <span class="js-emoji c-picker__emoji" title="elephant">🐘</span>
        <span class="js-emoji c-picker__emoji" title="panda_face">🐼</span>
        <span class="js-emoji c-picker__emoji" title="penguin">🐧</span>
        <span class="js-emoji c-picker__emoji" title="bird">🐦</span>
        <span class="js-emoji c-picker__emoji" title="baby_chick">🐤</span>
        <span class="js-emoji c-picker__emoji" title="hatched_chick">🐥</span>
        <span class="js-emoji c-picker__emoji" title="hatching_chick">🐣</span>
        <span class="js-emoji c-picker__emoji" title="chicken">🐔</span>
        <span class="js-emoji c-picker__emoji" title="snake">🐍</span>
        <span class="js-emoji c-picker__emoji" title="turtle">🐢</span>
        <span class="js-emoji c-picker__emoji" title="bug">🐛</span>
        <span class="js-emoji c-picker__emoji" title="bee">🐝</span>
        <span class="js-emoji c-picker__emoji" title="ant">🐜</span>
        <span class="js-emoji c-picker__emoji" title="beetle">🐞</span>
        <span class="js-emoji c-picker__emoji" title="snail">🐌</span>
        <span class="js-emoji c-picker__emoji" title="octopus">🐙</span>
        <span class="js-emoji c-picker__emoji" title="shell">🐚</span>
        <span class="js-emoji c-picker__emoji" title="tropical_fish">🐠</span>
        <span class="js-emoji c-picker__emoji" title="fish">🐟</span>
        <span class="js-emoji c-picker__emoji" title="dolphin">🐬</span>
        <span class="js-emoji c-picker__emoji" title="whale">🐳</span>
        <span class="js-emoji c-picker__emoji" title="racehorse">🐎</span>
        <span class="js-emoji c-picker__emoji" title="dragon_face">🐲</span>
        <span class="js-emoji c-picker__emoji" title="blowfish">🐡</span>
        <span class="js-emoji c-picker__emoji" title="camel">🐫</span>
        <span class="js-emoji c-picker__emoji" title="poodle">🐩</span>
        <span class="js-emoji c-picker__emoji" title="feet">🐾</span>
        <span class="js-emoji c-picker__emoji" title="bouquet">💐</span>
        <span class="js-emoji c-picker__emoji" title="cherry_blossom">🌸</span>
        <span class="js-emoji c-picker__emoji" title="tulip">🌷</span>
        <span class="js-emoji c-picker__emoji" title="four_leaf_clover">🍀</span>
        <span class="js-emoji c-picker__emoji" title="rose">🌹</span>
        <span class="js-emoji c-picker__emoji" title="sunflower">🌻</span>
        <span class="js-emoji c-picker__emoji" title="hibiscus">🌺</span>
        <span class="js-emoji c-picker__emoji" title="maple_leaf">🍁</span>
        <span class="js-emoji c-picker__emoji" title="leaves">🍃</span>
        <span class="js-emoji c-picker__emoji" title="fallen_leaf">🍂</span>
        <span class="js-emoji c-picker__emoji" title="herb">🌿</span>
        <span class="js-emoji c-picker__emoji" title="ear_of_rice">🌾</span>
        <span class="js-emoji c-picker__emoji" title="mushroom">🍄</span>
        <span class="js-emoji c-picker__emoji" title="cactus">🌵</span>
        <span class="js-emoji c-picker__emoji" title="palm_tree">🌴</span>
        <span class="js-emoji c-picker__emoji" title="chestnut">🌰</span>
        <span class="js-emoji c-picker__emoji" title="seedling">🌱</span>
        <span class="js-emoji c-picker__emoji" title="blossom">🌼</span>
        <span class="js-emoji c-picker__emoji" title="new_moon">🌑</span>
        <span class="js-emoji c-picker__emoji" title="first_quarter_moon">🌓</span>
        <span class="js-emoji c-picker__emoji" title="moon">🌔</span>
        <span class="js-emoji c-picker__emoji" title="full_moon">🌕</span>
        <span class="js-emoji c-picker__emoji" title="first_quarter_moon_with_face">🌛</span>
        <span class="js-emoji c-picker__emoji" title="crescent_moon">🌙</span>
        <span class="js-emoji c-picker__emoji" title="earth_asia">🌏</span>
        <span class="js-emoji c-picker__emoji" title="volcano">🌋</span>
        <span class="js-emoji c-picker__emoji" title="milky_way">🌌</span>
        <span class="js-emoji c-picker__emoji" title="stars">🌠</span>
        <span class="js-emoji c-picker__emoji" title="partly_sunny">⛅</span>
        <span class="js-emoji c-picker__emoji" title="snowman">⛄</span>
        <span class="js-emoji c-picker__emoji" title="cyclone">🌀</span>
        <span class="js-emoji c-picker__emoji" title="foggy">🌁</span>
        <span class="js-emoji c-picker__emoji" title="rainbow">🌈</span>
        <span class="js-emoji c-picker__emoji" title="ocean">🌊</span>
      </div>
      <div class=" c-picker__title">Objects</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="bamboo">🎍</span>
        <span class="js-emoji c-picker__emoji" title="gift_heart">💝</span>
        <span class="js-emoji c-picker__emoji" title="dolls">🎎</span>
        <span class="js-emoji c-picker__emoji" title="school_satchel">🎒</span>
        <span class="js-emoji c-picker__emoji" title="mortar_board">🎓</span>
        <span class="js-emoji c-picker__emoji" title="flags">🎏</span>
        <span class="js-emoji c-picker__emoji" title="fireworks">🎆</span>
        <span class="js-emoji c-picker__emoji" title="sparkler">🎇</span>
        <span class="js-emoji c-picker__emoji" title="wind_chime">🎐</span>
        <span class="js-emoji c-picker__emoji" title="rice_scene">🎑</span>
        <span class="js-emoji c-picker__emoji" title="jack_o_lantern">🎃</span>
        <span class="js-emoji c-picker__emoji" title="ghost">👻</span>
        <span class="js-emoji c-picker__emoji" title="santa">🎅</span>
        <span class="js-emoji c-picker__emoji" title="christmas_tree">🎄</span>
        <span class="js-emoji c-picker__emoji" title="gift">🎁</span>
        <span class="js-emoji c-picker__emoji" title="tanabata_tree">🎋</span>
        <span class="js-emoji c-picker__emoji" title="tada">🎉</span>
        <span class="js-emoji c-picker__emoji" title="confetti_ball">🎊</span>
        <span class="js-emoji c-picker__emoji" title="balloon">🎈</span>
        <span class="js-emoji c-picker__emoji" title="crossed_flags">🎌</span>
        <span class="js-emoji c-picker__emoji" title="crystal_ball">🔮</span>
        <span class="js-emoji c-picker__emoji" title="movie_camera">🎥</span>
        <span class="js-emoji c-picker__emoji" title="camera">📷</span>
        <span class="js-emoji c-picker__emoji" title="video_camera">📹</span>
        <span class="js-emoji c-picker__emoji" title="vhs">📼</span>
        <span class="js-emoji c-picker__emoji" title="cd">💿</span>
        <span class="js-emoji c-picker__emoji" title="dvd">📀</span>
        <span class="js-emoji c-picker__emoji" title="minidisc">💽</span>
        <span class="js-emoji c-picker__emoji" title="floppy_disk">💾</span>
        <span class="js-emoji c-picker__emoji" title="computer">💻</span>
        <span class="js-emoji c-picker__emoji" title="iphone">📱</span>
        <span class="js-emoji c-picker__emoji" title="telephone_receiver">📞</span>
        <span class="js-emoji c-picker__emoji" title="pager">📟</span>
        <span class="js-emoji c-picker__emoji" title="fax">📠</span>
        <span class="js-emoji c-picker__emoji" title="satellite">📡</span>
        <span class="js-emoji c-picker__emoji" title="tv">📺</span>
        <span class="js-emoji c-picker__emoji" title="radio">📻</span>
        <span class="js-emoji c-picker__emoji" title="loud_sound">🔊</span>
        <span class="js-emoji c-picker__emoji" title="bell">🔔</span>
        <span class="js-emoji c-picker__emoji" title="loudspeaker">📢</span>
        <span class="js-emoji c-picker__emoji" title="mega">📣</span>
        <span class="js-emoji c-picker__emoji" title="hourglass_flowing_sand">⏳</span>
        <span class="js-emoji c-picker__emoji" title="hourglass">⌛</span>
        <span class="js-emoji c-picker__emoji" title="alarm_clock">⏰</span>
        <span class="js-emoji c-picker__emoji" title="watch">⌚</span>
        <span class="js-emoji c-picker__emoji" title="unlock">🔓</span>
        <span class="js-emoji c-picker__emoji" title="lock">🔒</span>
        <span class="js-emoji c-picker__emoji" title="lock_with_ink_pen">🔏</span>
        <span class="js-emoji c-picker__emoji" title="closed_lock_with_key">🔐</span>
        <span class="js-emoji c-picker__emoji" title="key">🔑</span>
        <span class="js-emoji c-picker__emoji" title="mag_right">🔎</span>
        <span class="js-emoji c-picker__emoji" title="bulb">💡</span>
        <span class="js-emoji c-picker__emoji" title="flashlight">🔦</span>
        <span class="js-emoji c-picker__emoji" title="electric_plug">🔌</span>
        <span class="js-emoji c-picker__emoji" title="battery">🔋</span>
        <span class="js-emoji c-picker__emoji" title="mag">🔍</span>
        <span class="js-emoji c-picker__emoji" title="bath">🛀</span>
        <span class="js-emoji c-picker__emoji" title="toilet">🚽</span>
        <span class="js-emoji c-picker__emoji" title="wrench">🔧</span>
        <span class="js-emoji c-picker__emoji" title="nut_and_bolt">🔩</span>
        <span class="js-emoji c-picker__emoji" title="hammer">🔨</span>
        <span class="js-emoji c-picker__emoji" title="door">🚪</span>
        <span class="js-emoji c-picker__emoji" title="smoking">🚬</span>
        <span class="js-emoji c-picker__emoji" title="bomb">💣</span>
        <span class="js-emoji c-picker__emoji" title="gun">🔫</span>
        <span class="js-emoji c-picker__emoji" title="hocho">🔪</span>
        <span class="js-emoji c-picker__emoji" title="pill">💊</span>
        <span class="js-emoji c-picker__emoji" title="syringe">💉</span>
        <span class="js-emoji c-picker__emoji" title="moneybag">💰</span>
        <span class="js-emoji c-picker__emoji" title="yen">💴</span>
        <span class="js-emoji c-picker__emoji" title="dollar">💵</span>
        <span class="js-emoji c-picker__emoji" title="credit_card">💳</span>
        <span class="js-emoji c-picker__emoji" title="money_with_wings">💸</span>
        <span class="js-emoji c-picker__emoji" title="calling">📲</span>
        <span class="js-emoji c-picker__emoji" title="e-mail">📧</span>
        <span class="js-emoji c-picker__emoji" title="inbox_tray">📥</span>
        <span class="js-emoji c-picker__emoji" title="outbox_tray">📤</span>
        <span class="js-emoji c-picker__emoji" title="envelope_with_arrow">📩</span>
        <span class="js-emoji c-picker__emoji" title="incoming_envelope">📨</span>
        <span class="js-emoji c-picker__emoji" title="mailbox">📫</span>
        <span class="js-emoji c-picker__emoji" title="mailbox_closed">📪</span>
        <span class="js-emoji c-picker__emoji" title="postbox">📮</span>
        <span class="js-emoji c-picker__emoji" title="package">📦</span>
        <span class="js-emoji c-picker__emoji" title="memo">📝</span>
        <span class="js-emoji c-picker__emoji" title="page_facing_up">📄</span>
        <span class="js-emoji c-picker__emoji" title="page_with_curl">📃</span>
        <span class="js-emoji c-picker__emoji" title="bookmark_tabs">📑</span>
        <span class="js-emoji c-picker__emoji" title="bar_chart">📊</span>
        <span class="js-emoji c-picker__emoji" title="chart_with_upwards_trend">📈</span>
        <span class="js-emoji c-picker__emoji" title="chart_with_downwards_trend">📉</span>
        <span class="js-emoji c-picker__emoji" title="scroll">📜</span>
        <span class="js-emoji c-picker__emoji" title="clipboard">📋</span>
        <span class="js-emoji c-picker__emoji" title="date">📅</span>
        <span class="js-emoji c-picker__emoji" title="calendar">📆</span>
        <span class="js-emoji c-picker__emoji" title="card_index">📇</span>
        <span class="js-emoji c-picker__emoji" title="file_folder">📁</span>
        <span class="js-emoji c-picker__emoji" title="open_file_folder">📂</span>
        <span class="js-emoji c-picker__emoji" title="pushpin">📌</span>
        <span class="js-emoji c-picker__emoji" title="paperclip">📎</span>
        <span class="js-emoji c-picker__emoji" title="straight_ruler">📏</span>
        <span class="js-emoji c-picker__emoji" title="triangular_ruler">📐</span>
        <span class="js-emoji c-picker__emoji" title="closed_book">📕</span>
        <span class="js-emoji c-picker__emoji" title="green_book">📗</span>
        <span class="js-emoji c-picker__emoji" title="blue_book">📘</span>
        <span class="js-emoji c-picker__emoji" title="orange_book">📙</span>
        <span class="js-emoji c-picker__emoji" title="notebook">📓</span>
        <span class="js-emoji c-picker__emoji" title="notebook_with_decorative_cover">📔</span>
        <span class="js-emoji c-picker__emoji" title="ledger">📒</span>
        <span class="js-emoji c-picker__emoji" title="books">📚</span>
        <span class="js-emoji c-picker__emoji" title="book">📖</span>
        <span class="js-emoji c-picker__emoji" title="bookmark">🔖</span>
        <span class="js-emoji c-picker__emoji" title="name_badge">📛</span>
        <span class="js-emoji c-picker__emoji" title="newspaper">📰</span>
        <span class="js-emoji c-picker__emoji" title="art">🎨</span>
        <span class="js-emoji c-picker__emoji" title="clapper">🎬</span>
        <span class="js-emoji c-picker__emoji" title="microphone">🎤</span>
        <span class="js-emoji c-picker__emoji" title="headphones">🎧</span>
        <span class="js-emoji c-picker__emoji" title="musical_score">🎼</span>
        <span class="js-emoji c-picker__emoji" title="musical_note">🎵</span>
        <span class="js-emoji c-picker__emoji" title="notes">🎶</span>
        <span class="js-emoji c-picker__emoji" title="musical_keyboard">🎹</span>
        <span class="js-emoji c-picker__emoji" title="violin">🎻</span>
        <span class="js-emoji c-picker__emoji" title="trumpet">🎺</span>
        <span class="js-emoji c-picker__emoji" title="saxophone">🎷</span>
        <span class="js-emoji c-picker__emoji" title="guitar">🎸</span>
        <span class="js-emoji c-picker__emoji" title="space_invader">👾</span>
        <span class="js-emoji c-picker__emoji" title="video_game">🎮</span>
        <span class="js-emoji c-picker__emoji" title="black_joker">🃏</span>
        <span class="js-emoji c-picker__emoji" title="flower_playing_cards">🎴</span>
        <span class="js-emoji c-picker__emoji" title="mahjong">🀄</span>
        <span class="js-emoji c-picker__emoji" title="game_die">🎲</span>
        <span class="js-emoji c-picker__emoji" title="dart">🎯</span>
        <span class="js-emoji c-picker__emoji" title="football">🏈</span>
        <span class="js-emoji c-picker__emoji" title="basketball">🏀</span>
        <span class="js-emoji c-picker__emoji" title="soccer">⚽</span>
        <span class="js-emoji c-picker__emoji" title="baseball">⚾</span>
        <span class="js-emoji c-picker__emoji" title="tennis">🎾</span>
        <span class="js-emoji c-picker__emoji" title="8ball">🎱</span>
        <span class="js-emoji c-picker__emoji" title="bowling">🎳</span>
        <span class="js-emoji c-picker__emoji" title="golf">⛳</span>
        <span class="js-emoji c-picker__emoji" title="checkered_flag">🏁</span>
        <span class="js-emoji c-picker__emoji" title="trophy">🏆</span>
        <span class="js-emoji c-picker__emoji" title="ski">🎿</span>
        <span class="js-emoji c-picker__emoji" title="snowboarder">🏂</span>
        <span class="js-emoji c-picker__emoji" title="swimmer">🏊</span>
        <span class="js-emoji c-picker__emoji" title="surfer">🏄</span>
        <span class="js-emoji c-picker__emoji" title="fishing_pole_and_fish">🎣</span>
        <span class="js-emoji c-picker__emoji" title="tea">🍵</span>
        <span class="js-emoji c-picker__emoji" title="sake">🍶</span>
        <span class="js-emoji c-picker__emoji" title="beer">🍺</span>
        <span class="js-emoji c-picker__emoji" title="beers">🍻</span>
        <span class="js-emoji c-picker__emoji" title="cocktail">🍸</span>
        <span class="js-emoji c-picker__emoji" title="tropical_drink">🍹</span>
        <span class="js-emoji c-picker__emoji" title="wine_glass">🍷</span>
        <span class="js-emoji c-picker__emoji" title="fork_and_knife">🍴</span>
        <span class="js-emoji c-picker__emoji" title="pizza">🍕</span>
        <span class="js-emoji c-picker__emoji" title="hamburger">🍔</span>
        <span class="js-emoji c-picker__emoji" title="fries">🍟</span>
        <span class="js-emoji c-picker__emoji" title="poultry_leg">🍗</span>
        <span class="js-emoji c-picker__emoji" title="meat_on_bone">🍖</span>
        <span class="js-emoji c-picker__emoji" title="spaghetti">🍝</span>
        <span class="js-emoji c-picker__emoji" title="curry">🍛</span>
        <span class="js-emoji c-picker__emoji" title="fried_shrimp">🍤</span>
        <span class="js-emoji c-picker__emoji" title="bento">🍱</span>
        <span class="js-emoji c-picker__emoji" title="sushi">🍣</span>
        <span class="js-emoji c-picker__emoji" title="fish_cake">🍥</span>
        <span class="js-emoji c-picker__emoji" title="rice_ball">🍙</span>
        <span class="js-emoji c-picker__emoji" title="rice_cracker">🍘</span>
        <span class="js-emoji c-picker__emoji" title="rice">🍚</span>
        <span class="js-emoji c-picker__emoji" title="ramen">🍜</span>
        <span class="js-emoji c-picker__emoji" title="stew">🍲</span>
        <span class="js-emoji c-picker__emoji" title="oden">🍢</span>
        <span class="js-emoji c-picker__emoji" title="dango">🍡</span>
        <span class="js-emoji c-picker__emoji" title="egg">🍳</span>
        <span class="js-emoji c-picker__emoji" title="bread">🍞</span>
        <span class="js-emoji c-picker__emoji" title="doughnut">🍩</span>
        <span class="js-emoji c-picker__emoji" title="custard">🍮</span>
        <span class="js-emoji c-picker__emoji" title="icecream">🍦</span>
        <span class="js-emoji c-picker__emoji" title="ice_cream">🍨</span>
        <span class="js-emoji c-picker__emoji" title="shaved_ice">🍧</span>
        <span class="js-emoji c-picker__emoji" title="birthday">🎂</span>
        <span class="js-emoji c-picker__emoji" title="cake">🍰</span>
        <span class="js-emoji c-picker__emoji" title="cookie">🍪</span>
        <span class="js-emoji c-picker__emoji" title="chocolate_bar">🍫</span>
        <span class="js-emoji c-picker__emoji" title="candy">🍬</span>
        <span class="js-emoji c-picker__emoji" title="lollipop">🍭</span>
        <span class="js-emoji c-picker__emoji" title="honey_pot">🍯</span>
        <span class="js-emoji c-picker__emoji" title="apple">🍎</span>
        <span class="js-emoji c-picker__emoji" title="green_apple">🍏</span>
        <span class="js-emoji c-picker__emoji" title="tangerine">🍊</span>
        <span class="js-emoji c-picker__emoji" title="cherries">🍒</span>
        <span class="js-emoji c-picker__emoji" title="grapes">🍇</span>
        <span class="js-emoji c-picker__emoji" title="watermelon">🍉</span>
        <span class="js-emoji c-picker__emoji" title="strawberry">🍓</span>
        <span class="js-emoji c-picker__emoji" title="peach">🍑</span>
        <span class="js-emoji c-picker__emoji" title="melon">🍈</span>
        <span class="js-emoji c-picker__emoji" title="banana">🍌</span>
        <span class="js-emoji c-picker__emoji" title="pineapple">🍍</span>
        <span class="js-emoji c-picker__emoji" title="sweet_potato">🍠</span>
        <span class="js-emoji c-picker__emoji" title="eggplant">🍆</span>
        <span class="js-emoji c-picker__emoji" title="tomato">🍅</span>
        <span class="js-emoji c-picker__emoji" title="corn">🌽</span>
      </div>
      <div class=" c-picker__title">Places</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="house">🏠</span>
        <span class="js-emoji c-picker__emoji" title="house_with_garden">🏡</span>
        <span class="js-emoji c-picker__emoji" title="school">🏫</span>
        <span class="js-emoji c-picker__emoji" title="office">🏢</span>
        <span class="js-emoji c-picker__emoji" title="post_office">🏣</span>
        <span class="js-emoji c-picker__emoji" title="hospital">🏥</span>
        <span class="js-emoji c-picker__emoji" title="bank">🏦</span>
        <span class="js-emoji c-picker__emoji" title="convenience_store">🏪</span>
        <span class="js-emoji c-picker__emoji" title="love_hotel">🏩</span>
        <span class="js-emoji c-picker__emoji" title="hotel">🏨</span>
        <span class="js-emoji c-picker__emoji" title="wedding">💒</span>
        <span class="js-emoji c-picker__emoji" title="church">⛪</span>
        <span class="js-emoji c-picker__emoji" title="department_store">🏬</span>
        <span class="js-emoji c-picker__emoji" title="city_sunrise">🌇</span>
        <span class="js-emoji c-picker__emoji" title="city_sunset">🌆</span>
        <span class="js-emoji c-picker__emoji" title="japanese_castle">🏯</span>
        <span class="js-emoji c-picker__emoji" title="european_castle">🏰</span>
        <span class="js-emoji c-picker__emoji" title="tent">⛺</span>
        <span class="js-emoji c-picker__emoji" title="factory">🏭</span>
        <span class="js-emoji c-picker__emoji" title="tokyo_tower">🗼</span>
        <span class="js-emoji c-picker__emoji" title="japan">🗾</span>
        <span class="js-emoji c-picker__emoji" title="mount_fuji">🗻</span>
        <span class="js-emoji c-picker__emoji" title="sunrise_over_mountains">🌄</span>
        <span class="js-emoji c-picker__emoji" title="sunrise">🌅</span>
        <span class="js-emoji c-picker__emoji" title="night_with_stars">🌃</span>
        <span class="js-emoji c-picker__emoji" title="statue_of_liberty">🗽</span>
        <span class="js-emoji c-picker__emoji" title="bridge_at_night">🌉</span>
        <span class="js-emoji c-picker__emoji" title="carousel_horse">🎠</span>
        <span class="js-emoji c-picker__emoji" title="ferris_wheel">🎡</span>
        <span class="js-emoji c-picker__emoji" title="fountain">⛲</span>
        <span class="js-emoji c-picker__emoji" title="roller_coaster">🎢</span>
        <span class="js-emoji c-picker__emoji" title="ship">🚢</span>
        <span class="js-emoji c-picker__emoji" title="boat">⛵</span>
        <span class="js-emoji c-picker__emoji" title="speedboat">🚤</span>
        <span class="js-emoji c-picker__emoji" title="rocket">🚀</span>
        <span class="js-emoji c-picker__emoji" title="seat">💺</span>
        <span class="js-emoji c-picker__emoji" title="station">🚉</span>
        <span class="js-emoji c-picker__emoji" title="bullettrain_side">🚄</span>
        <span class="js-emoji c-picker__emoji" title="bullettrain_front">🚅</span>
        <span class="js-emoji c-picker__emoji" title="metro">🚇</span>
        <span class="js-emoji c-picker__emoji" title="railway_car">🚃</span>
        <span class="js-emoji c-picker__emoji" title="bus">🚌</span>
        <span class="js-emoji c-picker__emoji" title="blue_car">🚙</span>
        <span class="js-emoji c-picker__emoji" title="car">🚗</span>
        <span class="js-emoji c-picker__emoji" title="taxi">🚕</span>
        <span class="js-emoji c-picker__emoji" title="truck">🚚</span>
        <span class="js-emoji c-picker__emoji" title="rotating_light">🚨</span>
        <span class="js-emoji c-picker__emoji" title="police_car">🚓</span>
        <span class="js-emoji c-picker__emoji" title="fire_engine">🚒</span>
        <span class="js-emoji c-picker__emoji" title="ambulance">🚑</span>
        <span class="js-emoji c-picker__emoji" title="bike">🚲</span>
        <span class="js-emoji c-picker__emoji" title="barber">💈</span>
        <span class="js-emoji c-picker__emoji" title="busstop">🚏</span>
        <span class="js-emoji c-picker__emoji" title="ticket">🎫</span>
        <span class="js-emoji c-picker__emoji" title="traffic_light">🚥</span>
        <span class="js-emoji c-picker__emoji" title="construction">🚧</span>
        <span class="js-emoji c-picker__emoji" title="beginner">🔰</span>
        <span class="js-emoji c-picker__emoji" title="fuelpump">⛽</span>
        <span class="js-emoji c-picker__emoji" title="izakaya_lantern">🏮</span>
        <span class="js-emoji c-picker__emoji" title="slot_machine">🎰</span>
        <span class="js-emoji c-picker__emoji" title="moyai">🗿</span>
        <span class="js-emoji c-picker__emoji" title="circus_tent">🎪</span>
        <span class="js-emoji c-picker__emoji" title="performing_arts">🎭</span>
        <span class="js-emoji c-picker__emoji" title="round_pushpin">📍</span>
        <span class="js-emoji c-picker__emoji" title="triangular_flag_on_post">🚩</span>
      </div>
      <div class=" c-picker__title">Symbols</div>
      <div class="c-picker__group">
        <span class="js-emoji c-picker__emoji" title="keycap_ten">🔟</span>
        <span class="js-emoji c-picker__emoji" title="1234">🔢</span>
        <span class="js-emoji c-picker__emoji" title="symbols">🔣</span>
        <span class="js-emoji c-picker__emoji" title="capital_abcd">🔠</span>
        <span class="js-emoji c-picker__emoji" title="abcd">🔡</span>
        <span class="js-emoji c-picker__emoji" title="abc">🔤</span>
        <span class="js-emoji c-picker__emoji" title="arrow_up_small">🔼</span>
        <span class="js-emoji c-picker__emoji" title="arrow_down_small">🔽</span>
        <span class="js-emoji c-picker__emoji" title="rewind">⏪</span>
        <span class="js-emoji c-picker__emoji" title="fast_forward">⏩</span>
        <span class="js-emoji c-picker__emoji" title="arrow_double_up">⏫</span>
        <span class="js-emoji c-picker__emoji" title="arrow_double_down">⏬</span>
        <span class="js-emoji c-picker__emoji" title="ok">🆗</span>
        <span class="js-emoji c-picker__emoji" title="new">🆕</span>
        <span class="js-emoji c-picker__emoji" title="up">🆙</span>
        <span class="js-emoji c-picker__emoji" title="cool">🆒</span>
        <span class="js-emoji c-picker__emoji" title="free">🆓</span>
        <span class="js-emoji c-picker__emoji" title="ng">🆖</span>
        <span class="js-emoji c-picker__emoji" title="signal_strength">📶</span>
        <span class="js-emoji c-picker__emoji" title="cinema">🎦</span>
        <span class="js-emoji c-picker__emoji" title="koko">🈁</span>
        <span class="js-emoji c-picker__emoji" title="u6307">🈯</span>
        <span class="js-emoji c-picker__emoji" title="u7a7a">🈳</span>
        <span class="js-emoji c-picker__emoji" title="u6e80">🈵</span>
        <span class="js-emoji c-picker__emoji" title="u5408">🈴</span>
        <span class="js-emoji c-picker__emoji" title="u7981">🈲</span>
        <span class="js-emoji c-picker__emoji" title="ideograph_advantage">🉐</span>
        <span class="js-emoji c-picker__emoji" title="u5272">🈹</span>
        <span class="js-emoji c-picker__emoji" title="u55b6">🈺</span>
        <span class="js-emoji c-picker__emoji" title="u6709">🈶</span>
        <span class="js-emoji c-picker__emoji" title="u7121">🈚</span>
        <span class="js-emoji c-picker__emoji" title="restroom">🚻</span>
        <span class="js-emoji c-picker__emoji" title="mens">🚹</span>
        <span class="js-emoji c-picker__emoji" title="womens">🚺</span>
        <span class="js-emoji c-picker__emoji" title="baby_symbol">🚼</span>
        <span class="js-emoji c-picker__emoji" title="wc">🚾</span>
        <span class="js-emoji c-picker__emoji" title="no_smoking">🚭</span>
        <span class="js-emoji c-picker__emoji" title="u7533">🈸</span>
        <span class="js-emoji c-picker__emoji" title="accept">🉑</span>
        <span class="js-emoji c-picker__emoji" title="cl">🆑</span>
        <span class="js-emoji c-picker__emoji" title="sos">🆘</span>
        <span class="js-emoji c-picker__emoji" title="id">🆔</span>
        <span class="js-emoji c-picker__emoji" title="no_entry_sign">🚫</span>
        <span class="js-emoji c-picker__emoji" title="underage">🔞</span>
        <span class="js-emoji c-picker__emoji" title="no_entry">⛔</span>
        <span class="js-emoji c-picker__emoji" title="negative_squared_cross_mark">❎</span>
        <span class="js-emoji c-picker__emoji" title="white_check_mark">✅</span>
        <span class="js-emoji c-picker__emoji" title="heart_decoration">💟</span>
        <span class="js-emoji c-picker__emoji" title="vs">🆚</span>
        <span class="js-emoji c-picker__emoji" title="vibration_mode">📳</span>
        <span class="js-emoji c-picker__emoji" title="mobile_phone_off">📴</span>
        <span class="js-emoji c-picker__emoji" title="ab">🆎</span>
        <span class="js-emoji c-picker__emoji" title="diamond_shape_with_a_dot_inside">💠</span>
        <span class="js-emoji c-picker__emoji" title="ophiuchus">⛎</span>
        <span class="js-emoji c-picker__emoji" title="six_pointed_star">🔯</span>
        <span class="js-emoji c-picker__emoji" title="atm">🏧</span>
        <span class="js-emoji c-picker__emoji" title="chart">💹</span>
        <span class="js-emoji c-picker__emoji" title="heavy_dollar_sign">💲</span>
        <span class="js-emoji c-picker__emoji" title="currency_exchange">💱</span>
        <span class="js-emoji c-picker__emoji" title="x">❌</span>
        <span class="js-emoji c-picker__emoji" title="exclamation">❗</span>
        <span class="js-emoji c-picker__emoji" title="question">❓</span>
        <span class="js-emoji c-picker__emoji" title="grey_exclamation">❕</span>
        <span class="js-emoji c-picker__emoji" title="grey_question">❔</span>
        <span class="js-emoji c-picker__emoji" title="o">⭕</span>
        <span class="js-emoji c-picker__emoji" title="top">🔝</span>
        <span class="js-emoji c-picker__emoji" title="end">🔚</span>
        <span class="js-emoji c-picker__emoji" title="back">🔙</span>
        <span class="js-emoji c-picker__emoji" title="on">🔛</span>
        <span class="js-emoji c-picker__emoji" title="soon">🔜</span>
        <span class="js-emoji c-picker__emoji" title="arrows_clockwise">🔃</span>
        <span class="js-emoji c-picker__emoji" title="clock12">🕛</span>
        <span class="js-emoji c-picker__emoji" title="clock1">🕐</span>
        <span class="js-emoji c-picker__emoji" title="clock2">🕑</span>
        <span class="js-emoji c-picker__emoji" title="clock3">🕒</span>
        <span class="js-emoji c-picker__emoji" title="clock4">🕓</span>
        <span class="js-emoji c-picker__emoji" title="clock5">🕔</span>
        <span class="js-emoji c-picker__emoji" title="clock6">🕕</span>
        <span class="js-emoji c-picker__emoji" title="clock7">🕖</span>
        <span class="js-emoji c-picker__emoji" title="clock8">🕗</span>
        <span class="js-emoji c-picker__emoji" title="clock9">🕘</span>
        <span class="js-emoji c-picker__emoji" title="clock10">🕙</span>
        <span class="js-emoji c-picker__emoji" title="clock11">🕚</span>
        <span class="js-emoji c-picker__emoji" title="heavy_plus_sign">➕</span>
        <span class="js-emoji c-picker__emoji" title="heavy_minus_sign">➖</span>
        <span class="js-emoji c-picker__emoji" title="heavy_division_sign">➗</span>
        <span class="js-emoji c-picker__emoji" title="white_flower">💮</span>
        <span class="js-emoji c-picker__emoji" title="100">💯</span>
        <span class="js-emoji c-picker__emoji" title="radio_button">🔘</span>
        <span class="js-emoji c-picker__emoji" title="link">🔗</span>
        <span class="js-emoji c-picker__emoji" title="curly_loop">➰</span>
        <span class="js-emoji c-picker__emoji" title="trident">🔱</span>
        <span class="js-emoji c-picker__emoji" title="small_red_triangle">🔺</span>
        <span class="js-emoji c-picker__emoji" title="black_square_button">🔲</span>
        <span class="js-emoji c-picker__emoji" title="white_square_button">🔳</span>
        <span class="js-emoji c-picker__emoji" title="red_circle">🔴</span>
        <span class="js-emoji c-picker__emoji" title="large_blue_circle">🔵</span>
        <span class="js-emoji c-picker__emoji" title="small_red_triangle_down">🔻</span>
        <span class="js-emoji c-picker__emoji" title="white_large_square">⬜</span>
        <span class="js-emoji c-picker__emoji" title="black_large_square">⬛</span>
        <span class="js-emoji c-picker__emoji" title="large_orange_diamond">🔶</span>
        <span class="js-emoji c-picker__emoji" title="large_blue_diamond">🔷</span>
        <span class="js-emoji c-picker__emoji" title="small_orange_diamond">🔸</span>
        <span class="js-emoji c-picker__emoji" title="small_blue_diamond">🔹</span>
      </div>
    </div>
  </div>
</div>